EduHome/Models/Teacher.cs
using EduHome.Models.Common;

namespace EduHome.Models
{
    public class Teacher : BaseEntity
    {
        public string FullName { get; set; } = string.Empty;
        public string ImagePath { get; set; } = string.Empty;
        public string Profession { get; set; } = string.Empty;
        public int CourseId { get; set; }
        public Course Course { get; set; }

    }
}

EduHome/Areas/Admin/Controllers/TeacherController.cs
using System.Threading.Tasks;
using EduHome.Context;
using EduHome.Helpers;
using EduHome.Models;
using EduHome.ViewModel.TeacherViewModel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace EduHome.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class TeacherController : Controller
    {
        private readonly AppDbContext _context;
        private readonly IWebHostEnvironment _environment;
        private readonly string _folderPath;

        public TeacherController(AppDbContext context, IWebHostEnvironment environment)
        {
            _context = context;
            _environment = environment;
            _folderPath = Path.Combine(_environment.WebRootPath, "img", "teacher");
        }

        [HttpGet]
        public async Task<IActionResult> Update(int id)
        {
            await SendCoursesWithViewBag();

            var vm = await _context.Teachers.Select(x => new TeacherUpdateVm
            {
                Id = x.Id,
                FullName = x.FullName,
                CourseId = x.CourseId,
                Profession = x.Profession

            }).FirstOrDefaultAsync(x => x.Id == id);

            return View(vm);
        }


        [HttpPost]
        public async Task<IActionResult> Update(TeacherUpdateVm vm)
        {
            await SendCoursesWithViewBag();

            if (!ModelState.IsValid)
                return View(vm);

            if (!vm.Image?.CheckType() ?? false)
            {
                return View(vm);
            }

            var teacher = await _context.Teachers.FirstOrDefaultAsync(x => x.Id == vm.Id);

            if (teacher is null)
                return NotFound();

            if(vm.Image is { })
            {
                string folderPath = Path.Combine(_folderPath, teacher.ImagePath);

                if (System.IO.File.Exists(folderPath))
                    System.IO.File.Delete(folderPath);

                string uniqueFileName = await vm.Image.SaveFileAsync(_folderPath);
                teacher.ImagePath = uniqueFileName;

            }


            teacher.FullName = vm.FullName;
            teacher.CourseId = vm.CourseId;
            teacher.Profession = vm.Profession;

            _context.Teachers.Update(teacher);
            await _context.SaveChangesAsync();

            return RedirectToAction("Index");
        }


        public async Task<IActionResult> Delete(int id)
        {
            var teacher = await _context.Teachers.FirstOrDefaultAsync(x=>x.Id == id);

            if (teacher is null)
                return NotFound();

            _context.Teachers.Remove(teacher);
            await  _context.SaveChangesAsync();

            string folderPath = Path.Combine(_folderPath, teacher.ImagePath);

            if (System.IO.File.Exists(folderPath))
                System.IO.File.Delete(folderPath);

            return RedirectToAction("Index");

        }


        public async Task<IActionResult> Index()
        {
            var teachers = await _context.Teachers.Select(x => new TeacherGetVm
            {
                Id = x.Id,
                FullName = x.FullName,
                ImagePath = x.ImagePath,
                Profession = x.Profession

            }).ToListAsync();

            return View(teachers);
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            await SendCoursesWithViewBag();

            return View();
        }


        [HttpPost]
        public async Task<IActionResult> Create(TeacherCreateVm vm)
        {
            await SendCoursesWithViewBag();

            if (!ModelState.IsValid)
                return View(vm);

            if (!vm.Image.CheckType())
            {
                return View(vm);
            }

            string uniqueFileName = await vm.Image.SaveFileAsync(_folderPath);

            Teacher teacher = new()
            {
                FullName = vm.FullName,
                CourseId = vm.CourseId,
                Profession = vm.Profession,
                ImagePath = uniqueFileName
            };

            await _context.Teachers.AddAsync(teacher);
            await _context.SaveChangesAsync();

            return RedirectToAction("Index");

        }


        private async Task SendCoursesWithViewBag()
        {
            var courses = await _context.Courses.ToListAsync();

            ViewBag.Courses = courses;
        }
    }
}

EduHome/Controllers/TeacherController.cs
using System.Threading.Tasks;
using EduHome.Context;
using EduHome.ViewModel.TeacherViewModel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace EduHome.Controllers
{
    public class TeacherController(AppDbContext context) : Controller
    {
        public async Task<IActionResult> Index()
        {
            var teachers = await context.Teachers.Select(x => new TeacherGetVm
            {
                Id = x.Id,
                FullName = x.FullName,
                Profession = x.Profession,
                ImagePath = x.ImagePath
            })
                .ToListAsync();

            return View(teachers);
        }
    }
}

EduHome/Areas/Admin/Views/Teacher/Create.cshtml
@model TeacherCreateVm

<form method="post" enctype="multipart/form-data">

    <div class="form-group">
        <label for="FullName">Email FullName</label>
        <input asp-for="FullName" class="form-control" placeholder="Enter FullName">
        <span class="text-danger" asp-validation-for="FullName"></span>
    </div>

    <div class="form-group">
        <label for="Profession">Email Profession</label>
        <input asp-for="Profession" class="form-control" placeholder="Enter Profession">
        <span class="text-danger" asp-validation-for="Profession"></span>
    </div>
   
    <div class="form-group">
        <label for="Image">Email Image</label>
        <input asp-for="Image" class="form-control" placeholder="Enter Image">
        <span class="text-danger" asp-validation-for="Image"></span>
    </div>
    <div class="form-group" style="background-color: white">
        
        <select class="form-control" asp-for="CourseId">
            @foreach(Course course in ViewBag.Courses)
            {
                <option value="@course.Id" > @course.Title</option>
            }

        </select>

        <span class="text-danger" asp-validation-for="CourseId"></span>
    </div>


    <button type="submit" class="btn btn-primary">Submit</button>
</form>

EduHome/Areas/Admin/Views/Teacher/Index.cshtml
@model List<TeacherGetVm>

<table class="table">
    <thead>
        <a asp-action="Create" asp-controller="Teacher" class="btn btn-success">Create</a>

        <tr>
            <th scope="col">Id</th>
            <th scope="col">Fullname</th>
            <th scope="col">Profession</th>
            <th scope="col">Image</th>
            <th scope="col">Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach(var teacher in Model)
        {
            <tr>
                <th scope="row">@teacher.Id</th>
                <td>@teacher.FullName</td>
                <td>@teacher.Profession</td>
                <td>
                    <img src="~/img/teacher/@teacher.ImagePath" />
                </td>
                <td>
                    <a asp-action="Update" asp-route-id="@teacher.Id" class="btn btn-warning"> Update</a>
                    <a asp-action="Delete" asp-route-id ="@teacher.Id" class="btn btn-danger"> Delete</a>

                </td>

            </tr>
        }

       
        
    </tbody>
</table>

EduHome/Areas/Admin/Views/Teacher/Update.cshtml
@model TeacherUpdateVm

<form method="post" enctype="multipart/form-data">

    <div class="form-group">
        <label for="FullName">Email FullName</label>
        <input asp-for="FullName" class="form-control" placeholder="Enter FullName">
        <span class="text-danger" asp-validation-for="FullName"></span>
    </div>

    <div class="form-group">
        <label for="Profession">Email Profession</label>
        <input asp-for="Profession" class="form-control" placeholder="Enter Profession">
        <span class="text-danger" asp-validation-for="Profession"></span>
    </div>

    <div class="form-group">
        <label for="Image">Email Image</label>
        <input asp-for="Image" class="form-control" placeholder="Enter Image">
        <span class="text-danger" asp-validation-for="Image"></span>
    </div>
    <div class="form-group" style="background-color: white">

        <select class="form-control" asp-for="CourseId">
            @foreach (Course course in ViewBag.Courses)
            {
                <option value="@course.Id"> @course.Title</option>
            }

        </select>

        <span class="text-danger" asp-validation-for="CourseId"></span>
    </div>


    <button type="submit" class="btn btn-primary">Submit</button>
</form>